name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Base overview
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          config_display: large
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Europe/Paris
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-calendar.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_other: yes
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 30
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: yes
          config_timezone: Europe/Paris
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Starred repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-stars.svg
          base: ""
          plugin_stars: yes
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Starred topics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-topics.svg
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 30
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, push
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Notable contributions
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-notable.svg
          base: ""
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit, pull_request, issue
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Repository contributors
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: repository
          repo: bynaryman.github.io
          filename: assets/metrics/metrics-contributors.svg
          base: ""
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_contributors_sections: contributors
          committer_branch: master
          committer_message: "chore: update metrics"
