name: Metrics
on:
  # Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Base overview
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          config_display: large
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Europe/Paris
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-calendar.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 10
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_other: yes
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 30
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Starred repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-stars.svg
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 12
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Notable contributions
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-notable.svg
          base: ""
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_self: no
          plugin_notable_types: commit, pull_request, issue
          committer_branch: master
          committer_message: "chore: update metrics"
