name: GitHub Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Base overview
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          config_display: large
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Europe/Paris
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          config_timezone: Europe/Paris
          committer_branch: master
          committer_message: "chore: update metrics"

      - name: Starred repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bynaryman
          template: classic
          filename: assets/metrics/metrics-stars.svg
          base: ""
          plugin_stars: yes
          committer_branch: master
          committer_message: "chore: update metrics"
